language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t himcgyver/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true himcgyver/docker-react npm run test